Update pt.json
saadeghi/daisyui pull request #2744
Opened 2024-01-09 19:46 UTC by bernardoamorim7

From line 404 to line 463.

Other portuguese speakers might want to give a look too.

2024-01-11 00:02 UTC, saadeghi requested changes

2024-01-11 00:02 UTC, saadeghi commented on src/docs/src/translation/pt.json
> -  "Join": "Join",
Please don't delete lines, even if it doesn't need translation, keep it as it is (with English string) because it helps comparing JSON files together and find missing translations.

2024-01-11 00:02 UTC, saadeghi commented on src/docs/src/translation/pt.json
> -  "Loading": "Loading",
Also

2024-01-11 00:02 UTC, saadeghi commented on src/docs/src/translation/pt.json
> -  "related projects": "related projects",
Also

2024-01-11 00:02 UTC, saadeghi commented on src/docs/src/translation/pt.json
> -  "Browser mockup": "Browser mockup",
Also

2024-01-11 00:02 UTC, saadeghi commented on src/docs/src/translation/pt.json
> -  "Browser": "Browser",
Also

2024-01-12 02:47 UTC, bernardoamorim7 commented
I apologize, didn't even see that when submitting the PR.
Should be fixed now, plus other mistakes I found on the translated part.

2024-01-12 02:50 UTC, merged

2024-01-12 02:50 UTC, saadeghi commented
Thanks!