Feat/comment
saadeghi/daisyui pull request #949
Opened 2022-07-15 06:00 UTC by imanmalekian31

New Comment component.

2022-08-28 16:06 UTC, PadowYT2 requested changes

2022-08-28 16:06 UTC, PadowYT2 commented on src/components/unstyled/comment.css
> +    @apply flex flex-col;
This was a bad change, without it, the image and the text are linked

2022-09-28 19:51 UTC, taylorjdawson commented
@imanmalekian31 @PadowYT2 what is the status on this?

2022-09-29 05:47 UTC, imanmalekian31 commented
@taylorjdawson, @saadeghi should answer it :)

2022-09-30 14:35 UTC, PadowYT2 commented
And I'm not a dev, just a user

2022-10-02 19:00 UTC, saadeghi commented
It's on hold. We need to be careful.  
I know it's exciting to get new components faster but of we don't consider all use cases for a component, we will have unnecessary breaking changes, forcing everyone to change their HTML, and that's not good at all.  
I hope you understand and give it time because reviewing PRs like this is not just reviewing the code. It's about design and testing it will all possible common use cases a designer may think of for that specific component.

2023-06-01 02:42 UTC, saadeghi commented
Moving forward with version `3.0` I have no plans for adding a `comment` class for now. There are many designs that can be implemented and we need to be flexible with that however the main difference between different designs of a comment box is mostly the grid/flex layout which is already easy to make using Tailwind utility classes.

Thanks for the PR

2023-06-01 02:42 UTC, closed without merging